# Generated by Django 6.0.1 on 2026-01-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
