# Generated by Django 6.0.1 on 2026-01-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='crm.product'),
        ),
    ]
