# Generated by Django 6.0.1 on 2026-02-02 23:13

import apps.crm.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_decimal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='services_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), apps.crm.models.validate_duration_minutes])),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='crm.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='crm.service')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='crm.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='transactions', through='crm.TransactionService', to='crm.service'),
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='crm.company')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_services', to='crm.transaction')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='crm.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='crm_clients_client__8e5801_idx'), models.Index(fields=['client', 'ends_at'], name='crm_clients_client__16c98f_idx'), models.Index(fields=['company', 'status'], name='crm_clients_company_192abf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transactionservice',
            index=models.Index(fields=['transaction', 'service'], name='crm_transac_transac_b322db_idx'),
        ),
    ]
