# Generated by Django 6.0.1 on 2026-02-03 00:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


def copy_transaction_products(apps, schema_editor):
    Transaction = apps.get_model("crm", "Transaction")
    TransactionProduct = apps.get_model("crm", "TransactionProduct")
    products_field = Transaction._meta.get_field("products")
    through_model = products_field.remote_field.through

    if through_model is None:
        return

    rows = list(through_model.objects.all().values_list("transaction_id", "product_id"))
    if not rows:
        return

    TransactionProduct.objects.bulk_create(
        [
            TransactionProduct(transaction_id=transaction_id, product_id=product_id)
            for transaction_id, product_id in rows
        ],
        batch_size=1000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_transaction_services_starts_at_service_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionProduct",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_items",
                        to="crm.product",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_items",
                        to="crm.transaction",
                    ),
                ),
            ],
        ),
        migrations.RunPython(copy_transaction_products, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="transaction",
            name="products",
        ),
        migrations.AddField(
            model_name="transaction",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="transactions",
                through="crm.TransactionProduct",
                to="crm.product",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionproduct",
            index=models.Index(fields=["transaction", "product"], name="crm_transac_transac_77b02f_idx"),
        ),
    ]
