# Generated by Django 6.0.1 on 2026-03-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_transaction_products_through'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transactionproduct',
            new_name='crm_transac_transac_934395_idx',
            old_name='crm_transac_transac_77b02f_idx',
        ),
    ]
