# Generated by Django 6.0.1 on 2026-03-04

from django.db import migrations


def migrate_members_json_to_companymember(apps, schema_editor):
    Company = apps.get_model("crm", "Company")
    CompanyMember = apps.get_model("crm", "CompanyMember")
    User = apps.get_model("users", "User")

    for company in Company.objects.all().iterator():
        raw_members = getattr(company, "members", None) or []
        if not isinstance(raw_members, list):
            continue

        for raw_member in raw_members:
            if not isinstance(raw_member, dict):
                continue

            user_id = raw_member.get("id")
            if not user_id:
                continue

            telegram_id = raw_member.get("telegram_id")
            try:
                if not User.objects.filter(pk=user_id).exists():
                    continue
            except (ValueError, TypeError):
                continue

            membership, created = CompanyMember.objects.get_or_create(
                company_id=company.pk,
                user_id=user_id,
                defaults={"telegram_id": telegram_id},
            )
            if not created and telegram_id is not None and membership.telegram_id != telegram_id:
                membership.telegram_id = telegram_id
                membership.save(update_fields=["telegram_id"])


def migrate_companymember_to_members_json(apps, schema_editor):
    Company = apps.get_model("crm", "Company")
    CompanyMember = apps.get_model("crm", "CompanyMember")

    for company in Company.objects.all().iterator():
        members = [
            {"id": str(user_id), "telegram_id": telegram_id}
            for user_id, telegram_id in CompanyMember.objects.filter(
                company_id=company.pk
            ).values_list("user_id", "telegram_id")
        ]
        company.members = members
        company.save(update_fields=["members"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_rename_crm_transac_transac_77b02f_idx_crm_transac_transac_934395_idx"),
    ]

    operations = [
        migrations.RunPython(
            migrate_members_json_to_companymember,
            reverse_code=migrate_companymember_to_members_json,
        ),
        migrations.RemoveField(
            model_name="company",
            name="members",
        ),
    ]
