# Generated by Django 6.0.1 on 2026-03-04 00:00

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(
                blank=True, default=apps.users.models.default_user_preferences
            ),
        ),
    ]
